import type { Metadata } from "next";
import Nav from "@/components/Nav";
import "./globals.css";
import { ttCommons } from "@/fonts";
import NavMobileProvider from "@/context/NavMobileProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <NavMobileProvider>
      <html lang="en">
        <body className={`${ttCommons.className} relative bg-[#ebebeb]`}>
          <Nav />
          {children}
        </body>
      </html>
    </NavMobileProvider>
  );
}
